create extension if not exists pgcrypto;

create table if not exists public.countries (
  code text primary key,
  name text not null,
  currency_code text not null,
  currency_symbol text not null,
  currency_name text not null,
  is_supported boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.roles (
  id integer primary key,
  name text not null unique,
  description text,
  can_create_company boolean not null default false,
  can_manage_users boolean not null default false,
  can_approve_accounts boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.permissions (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text not null default '',
  category text not null default 'General',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.role_permissions (
  id integer generated by default as identity primary key,
  role_id integer not null references public.roles(id) on delete cascade,
  permission_id integer not null references public.permissions(id) on delete cascade,
  is_granted boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (role_id, permission_id)
);

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  address text,
  country_code text not null references public.countries(code),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  cell_number text,
  role_id integer references public.roles(id),
  role text not null default 'tenant',
  company_id uuid references public.companies(id),
  status text not null default 'active',
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_permissions (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  permission_id integer not null references public.permissions(id) on delete cascade,
  is_granted boolean not null default true,
  granted_by_user_id uuid not null references auth.users(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  unique (user_id, permission_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists companies_set_updated_at on public.companies;
create trigger companies_set_updated_at
before update on public.companies
for each row execute procedure public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  metadata jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  target_role text := lower(coalesce(metadata ->> 'role', 'tenant'));
  target_role_id integer;
  target_company_name text := nullif(trim(coalesce(metadata ->> 'companyName', '')), '');
  target_country_code text := upper(coalesce(metadata ->> 'countryCode', 'ZA'));
  target_company_id uuid;
begin
  target_role_id := (
    select id
    from public.roles
    where lower(name) = target_role
    limit 1
  );

  if target_company_name is not null then
    target_company_id := (
      select id
      from public.companies
      where lower(name) = lower(target_company_name)
      limit 1
    );

    if target_company_id is null then
      insert into public.companies (name, country_code)
      values (target_company_name, target_country_code)
      returning id into target_company_id;
    end if;
  end if;

  insert into public.profiles (
    id,
    email,
    full_name,
    cell_number,
    role_id,
    role,
    company_id,
    status
  )
  values (
    new.id,
    new.email,
    coalesce(metadata ->> 'fullName', metadata ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(metadata ->> 'cellNumber', metadata ->> 'phone'),
    target_role_id,
    target_role,
    target_company_id,
    lower(coalesce(metadata ->> 'status', 'active'))
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = excluded.full_name,
      cell_number = excluded.cell_number,
      role_id = excluded.role_id,
      role = excluded.role,
      company_id = excluded.company_id,
      status = excluded.status,
      updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

create or replace function public.get_effective_permissions(target_user_id uuid)
returns table (code text, is_granted boolean)
language sql
security definer
set search_path = public
as $$
  with role_defaults as (
    select p.code, rp.is_granted
    from public.profiles pr
    join public.role_permissions rp on rp.role_id = pr.role_id
    join public.permissions p on p.id = rp.permission_id
    where pr.id = target_user_id
  ),
  user_overrides as (
    select p.code, up.is_granted
    from public.user_permissions up
    join public.permissions p on p.id = up.permission_id
    where up.user_id = target_user_id
  )
  select code, is_granted from role_defaults
  union
  select code, is_granted from user_overrides;
$$;

alter table public.countries enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.user_permissions enable row level security;

drop policy if exists countries_read on public.countries;
create policy countries_read on public.countries
for select using (true);

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
for select using (auth.role() = 'authenticated');

drop policy if exists permissions_read on public.permissions;
create policy permissions_read on public.permissions
for select using (auth.role() = 'authenticated');

drop policy if exists role_permissions_read on public.role_permissions;
create policy role_permissions_read on public.role_permissions
for select using (auth.role() = 'authenticated');

drop policy if exists profiles_read_same_company on public.profiles;
create policy profiles_read_same_company on public.profiles
for select using (
  auth.uid() = id
  or exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id is not null
      and current_profile.company_id = profiles.company_id
  )
);

drop policy if exists profiles_update_self_or_manager on public.profiles;
create policy profiles_update_self_or_manager on public.profiles
for update using (
  auth.uid() = id
  or exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = profiles.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager')
  )
)
with check (
  auth.uid() = id
  or exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = profiles.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager')
  )
);

drop policy if exists companies_read_same_company on public.companies;
create policy companies_read_same_company on public.companies
for select using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = companies.id
  )
);

drop policy if exists companies_update_admin on public.companies;
create policy companies_update_admin on public.companies
for update using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = companies.id
      and lower(current_profile.role) in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = companies.id
      and lower(current_profile.role) in ('owner', 'admin')
  )
);

drop policy if exists user_permissions_read_same_company on public.user_permissions;
create policy user_permissions_read_same_company on public.user_permissions
for select using (
  exists (
    select 1
    from public.profiles target_profile
    join public.profiles current_profile on current_profile.id = auth.uid()
    where target_profile.id = user_permissions.user_id
      and current_profile.company_id = target_profile.company_id
  )
);

drop policy if exists user_permissions_manage_admin on public.user_permissions;
create policy user_permissions_manage_admin on public.user_permissions
for all using (
  exists (
    select 1
    from public.profiles current_profile
    join public.profiles target_profile on target_profile.id = user_permissions.user_id
    where current_profile.id = auth.uid()
      and current_profile.company_id = target_profile.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager')
  )
)
with check (
  exists (
    select 1
    from public.profiles current_profile
    join public.profiles target_profile on target_profile.id = user_permissions.user_id
    where current_profile.id = auth.uid()
      and current_profile.company_id = target_profile.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager')
  )
);

insert into public.countries (code, name, currency_code, currency_symbol, currency_name, is_supported)
values
  ('ZA', 'South Africa', 'ZAR', 'R', 'South African Rand', true),
  ('NG', 'Nigeria', 'NGN', '₦', 'Nigerian Naira', true),
  ('KE', 'Kenya', 'KES', 'KSh', 'Kenyan Shilling', true),
  ('US', 'United States', 'USD', '$', 'US Dollar', true),
  ('GB', 'United Kingdom', 'GBP', '£', 'British Pound Sterling', true),
  ('AE', 'United Arab Emirates', 'AED', 'AED', 'UAE Dirham', true),
  ('AU', 'Australia', 'AUD', '$', 'Australian Dollar', true),
  ('CA', 'Canada', 'CAD', '$', 'Canadian Dollar', true)
on conflict (code) do update
set name = excluded.name,
    currency_code = excluded.currency_code,
    currency_symbol = excluded.currency_symbol,
    currency_name = excluded.currency_name,
    is_supported = excluded.is_supported;

insert into public.roles (id, name, description, can_create_company, can_manage_users, can_approve_accounts)
values
  (1, 'tenant', 'Tenant access', false, false, false),
  (2, 'agent', 'Leasing agent', false, false, false),
  (3, 'property_manager', 'Property manager', true, true, true),
  (4, 'owner', 'Company owner', true, true, true),
  (5, 'landlord', 'Landlord', true, true, true),
  (6, 'admin', 'Company admin', true, true, true)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    can_create_company = excluded.can_create_company,
    can_manage_users = excluded.can_manage_users,
    can_approve_accounts = excluded.can_approve_accounts;

insert into public.permissions (code, name, description, category)
values
  ('create_application_link', 'Create Application Links', 'Create shareable application links.', 'Applications'),
  ('view_applications', 'View Applications', 'View submitted rental applications.', 'Applications'),
  ('review_applications', 'Review Applications', 'Review and process applications.', 'Applications'),
  ('approve_applications', 'Approve Applications', 'Approve or reject applications.', 'Applications'),
  ('generate_lease', 'Generate Lease', 'Generate lease documents.', 'Leases'),
  ('send_lease', 'Send Lease', 'Send lease documents for signing.', 'Leases'),
  ('approve_lease', 'Approve Lease', 'Approve finalized leases.', 'Leases'),
  ('create_units', 'Create Units', 'Create property units.', 'Units'),
  ('edit_units', 'Edit Units', 'Edit property units.', 'Units'),
  ('delete_units', 'Delete Units', 'Delete property units.', 'Units'),
  ('view_users', 'View Users', 'View company users.', 'Users'),
  ('invite_users', 'Invite Users', 'Invite or create company users.', 'Users'),
  ('approve_users', 'Approve Users', 'Approve provisional users.', 'Users'),
  ('change_roles', 'Change Roles', 'Change user roles.', 'Users'),
  ('remove_users', 'Remove Users', 'Remove or block users.', 'Users'),
  ('manage_permissions', 'Manage Permissions', 'Manage granular permission overrides.', 'Configuration'),
  ('view_settings', 'View Settings', 'View settings and configuration.', 'Configuration'),
  ('edit_company_settings', 'Edit Company Settings', 'Edit company settings.', 'Configuration'),
  ('view_financials', 'View Financials', 'View billing and financial data.', 'Financials'),
  ('manage_billing', 'Manage Billing', 'Manage billing and payment settings.', 'Financials')
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    category = excluded.category;

insert into public.role_permissions (role_id, permission_id, is_granted)
select r.id, p.id, true
from public.roles r
join public.permissions p on p.code in (
  'create_application_link',
  'view_applications',
  'review_applications',
  'approve_applications',
  'generate_lease',
  'send_lease',
  'approve_lease',
  'create_units',
  'edit_units',
  'delete_units',
  'view_users',
  'invite_users',
  'approve_users',
  'change_roles',
  'remove_users',
  'manage_permissions',
  'view_settings',
  'edit_company_settings',
  'view_financials',
  'manage_billing'
)
where lower(r.name) in ('owner', 'landlord', 'admin', 'property_manager')
on conflict (role_id, permission_id) do update
set is_granted = excluded.is_granted;

create table if not exists public.estates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  address text,
  city text,
  province text,
  postal_code text,
  company_id uuid not null references public.companies(id) on delete cascade,
  company_name text,
  total_units integer not null default 0,
  contact_email text,
  contact_phone text,
  images text,
  amenities text,
  logo_blob_name text,
  logo_url text,
  status text not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.units (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  company_name text,
  estate_id uuid references public.estates(id) on delete set null,
  estate_name text,
  name text not null,
  address text,
  rent numeric(12,2) not null default 0,
  deposit numeric(12,2) not null default 0,
  bedrooms integer not null default 0,
  bathrooms numeric(6,2) not null default 0,
  sqft numeric(12,2) not null default 0,
  status text not null default 'vacant',
  description text,
  images text,
  billing_cycle text,
  package_breakdown text,
  initial_charges_breakdown text,
  fees text,
  initial_charges numeric(12,2) not null default 0,
  initial_total_pay numeric(12,2) not null default 0,
  apartment_number text,
  amenities text,
  lease_history text,
  pending_applications integer not null default 0,
  lease_start timestamptz,
  lease_term text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.application_links (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  cell_number text not null,
  id_number text,
  unit_id uuid references public.units(id) on delete set null,
  requires_credit_check boolean not null default true,
  agent_id uuid references public.profiles(id) on delete set null,
  lease_start_date timestamptz,
  lease_duration_months integer not null default 12,
  company_id uuid references public.companies(id) on delete set null,
  status text not null default 'link_created',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.applications (
  id uuid primary key,
  application_link_id uuid references public.application_links(id) on delete set null,
  full_name text not null,
  cell_number text not null,
  id_number text,
  email text,
  salary numeric(14,2),
  employer text,
  employment_status text,
  employment_duration text,
  country text default 'ZA',
  unit_id uuid references public.units(id) on delete set null,
  company_id uuid references public.companies(id) on delete set null,
  agent_id uuid references public.profiles(id) on delete set null,
  tenant_user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'link_created',
  requires_credit_check boolean not null default true,
  has_account boolean not null default false,
  initial_payment_paid boolean not null default false,
  lease_start_date timestamptz,
  lease_duration_months integer not null default 12,
  lease_pdf_path text,
  signed_lease_path text,
  credit_report_data jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.application_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  document_type text not null,
  file_path text not null,
  file_name text not null,
  file_size bigint not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists estates_set_updated_at on public.estates;
create trigger estates_set_updated_at
before update on public.estates
for each row execute procedure public.set_updated_at();

drop trigger if exists units_set_updated_at on public.units;
create trigger units_set_updated_at
before update on public.units
for each row execute procedure public.set_updated_at();

drop trigger if exists application_links_set_updated_at on public.application_links;
create trigger application_links_set_updated_at
before update on public.application_links
for each row execute procedure public.set_updated_at();

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
before update on public.applications
for each row execute procedure public.set_updated_at();

alter table public.estates enable row level security;
alter table public.units enable row level security;
alter table public.application_links enable row level security;
alter table public.applications enable row level security;
alter table public.application_documents enable row level security;

drop policy if exists estates_read_same_company on public.estates;
create policy estates_read_same_company on public.estates
for select using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = estates.company_id
  )
);

drop policy if exists estates_manage_admin on public.estates;
create policy estates_manage_admin on public.estates
for all using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = estates.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
)
with check (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = estates.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
);

drop policy if exists units_read_same_company on public.units;
create policy units_read_same_company on public.units
for select using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id is not null
      and current_profile.company_id = units.company_id
  )
);

drop policy if exists units_manage_same_company on public.units;
create policy units_manage_same_company on public.units
for all using (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = units.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
)
with check (
  exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and current_profile.company_id = units.company_id
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
);

drop policy if exists application_links_public_select on public.application_links;
create policy application_links_public_select on public.application_links
for select using (true);

drop policy if exists application_links_manage_same_company on public.application_links;
create policy application_links_manage_same_company on public.application_links
for all using (
  auth.uid() is null
  or exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and (
        application_links.company_id is null
        or current_profile.company_id = application_links.company_id
      )
  )
)
with check (
  auth.uid() is null
  or exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and (
        application_links.company_id is null
        or current_profile.company_id = application_links.company_id
      )
  )
);

drop policy if exists applications_public_read_update on public.applications;
create policy applications_public_read_update on public.applications
for select using (true);

drop policy if exists applications_public_insert_update on public.applications;
create policy applications_public_insert_update on public.applications
for all using (true)
with check (true);

drop policy if exists application_documents_public_read on public.application_documents;
create policy application_documents_public_read on public.application_documents
for select using (true);

drop policy if exists application_documents_public_manage on public.application_documents;
create policy application_documents_public_manage on public.application_documents
for all using (true)
with check (true);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  message text not null,
  action_url text,
  related_entity_id text,
  related_entity_type text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  unit_id uuid references public.units(id) on delete set null,
  estate_id uuid references public.estates(id) on delete set null,
  maintenance_request_id uuid,
  type text not null default 'Direct',
  subject text not null,
  status text not null default 'Active',
  created_by_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  closed_at timestamptz
);

create table if not exists public.conversation_participants (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'Participant',
  joined_at timestamptz not null default timezone('utc', now()),
  left_at timestamptz,
  last_read_at timestamptz,
  unread_count integer not null default 0,
  is_muted boolean not null default false,
  unique (conversation_id, user_id)
);

create table if not exists public.conversation_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  sender_name text,
  sender_role text,
  content text not null,
  type text not null default 'Text',
  status text not null default 'Sent',
  reply_to_message_id uuid references public.conversation_messages(id) on delete set null,
  metadata text,
  edited_at timestamptz,
  deleted_at timestamptz,
  is_deleted boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.conversation_message_reads (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.conversation_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default timezone('utc', now()),
  unique (message_id, user_id)
);

create table if not exists public.maintenance_requests (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  unit_id uuid references public.units(id) on delete set null,
  tenant_user_id uuid references public.profiles(id) on delete set null,
  tenant_name text,
  lease_id uuid,
  title text not null,
  description text not null,
  category text not null,
  priority text not null default 'Medium',
  status text not null default 'Open',
  assigned_to text,
  assigned_to_user_id uuid references public.profiles(id) on delete set null,
  preferred_contact_method text,
  availability text,
  permission_to_enter boolean not null default false,
  estimated_cost numeric(14,2),
  actual_cost numeric(14,2),
  internal_notes text,
  resolution_notes text,
  satisfaction_rating integer,
  tenant_feedback text,
  due_date timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.maintenance_activities (
  id uuid primary key default gen_random_uuid(),
  maintenance_request_id uuid not null references public.maintenance_requests(id) on delete cascade,
  performed_by_user_id uuid not null references public.profiles(id) on delete cascade,
  performed_by_name text not null,
  activity_type text not null,
  description text not null,
  old_value text,
  new_value text,
  is_visible_to_tenant boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists conversations_set_updated_at on public.conversations;
create trigger conversations_set_updated_at
before update on public.conversations
for each row execute procedure public.set_updated_at();

drop trigger if exists maintenance_requests_set_updated_at on public.maintenance_requests;
create trigger maintenance_requests_set_updated_at
before update on public.maintenance_requests
for each row execute procedure public.set_updated_at();

alter table public.notifications enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.conversation_messages enable row level security;
alter table public.conversation_message_reads enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.maintenance_activities enable row level security;

drop policy if exists notifications_read_policy on public.notifications;
create policy notifications_read_policy on public.notifications
for select using (
  auth.role() = 'authenticated'
  and (
    notifications.user_id is null
    or notifications.user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = notifications.company_id
    )
  )
);

drop policy if exists notifications_manage_policy on public.notifications;
create policy notifications_manage_policy on public.notifications
for all using (
  auth.role() = 'authenticated'
  and (
    notifications.user_id is null
    or notifications.user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = notifications.company_id
    )
  )
)
with check (auth.role() = 'authenticated');

drop policy if exists conversations_read_policy on public.conversations;
create policy conversations_read_policy on public.conversations
for select using (
  auth.role() = 'authenticated'
  and (
    conversations.created_by_user_id = auth.uid()
    or exists (
      select 1
      from public.conversation_participants cp
      where cp.conversation_id = conversations.id
        and cp.user_id = auth.uid()
    )
  )
);

drop policy if exists conversations_manage_policy on public.conversations;
create policy conversations_manage_policy on public.conversations
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists conversation_participants_policy on public.conversation_participants;
create policy conversation_participants_policy on public.conversation_participants
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists conversation_messages_policy on public.conversation_messages;
create policy conversation_messages_policy on public.conversation_messages
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists conversation_message_reads_policy on public.conversation_message_reads;
create policy conversation_message_reads_policy on public.conversation_message_reads
for all using (
  auth.role() = 'authenticated'
  and conversation_message_reads.user_id = auth.uid()
)
with check (
  auth.role() = 'authenticated'
  and conversation_message_reads.user_id = auth.uid()
);

drop policy if exists maintenance_requests_policy on public.maintenance_requests;
create policy maintenance_requests_policy on public.maintenance_requests
for all using (
  auth.role() = 'authenticated'
  and (
    maintenance_requests.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = maintenance_requests.company_id
    )
  )
)
with check (
  auth.role() = 'authenticated'
  and (
    maintenance_requests.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = maintenance_requests.company_id
    )
  )
);

drop policy if exists maintenance_activities_policy on public.maintenance_activities;
create policy maintenance_activities_policy on public.maintenance_activities
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create table if not exists public.lease_templates (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  company_name text,
  name text not null,
  content text not null,
  is_default boolean not null default false,
  created_by_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lease_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  company_id uuid references public.companies(id) on delete set null,
  content text,
  status text not null default 'draft',
  created_by_user_id uuid references public.profiles(id) on delete set null,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.additional_charges (
  id uuid primary key default gen_random_uuid(),
  application_id uuid references public.applications(id) on delete cascade,
  unit_id uuid references public.units(id) on delete set null,
  tenant_user_id uuid references public.profiles(id) on delete set null,
  company_id uuid references public.companies(id) on delete set null,
  charge_type text not null default 'other',
  description text not null,
  amount numeric(14,2) not null default 0,
  billing_month text not null,
  status text not null default 'pending',
  created_by_user_id uuid references public.profiles(id) on delete set null,
  created_by_role text,
  supporting_document_ids text,
  due_date timestamptz,
  paid_at timestamptz,
  payment_transaction_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.additional_charge_appeals (
  id uuid primary key default gen_random_uuid(),
  additional_charge_id uuid not null references public.additional_charges(id) on delete cascade,
  tenant_user_id uuid references public.profiles(id) on delete set null,
  reason text not null,
  supporting_document_ids text,
  status text not null default 'pending',
  reviewer_response text,
  reviewed_by_user_id uuid references public.profiles(id) on delete set null,
  reviewed_by_role text,
  reviewed_at timestamptz,
  adjusted_amount numeric(14,2),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tenant_payments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete set null,
  tenant_user_id uuid references public.profiles(id) on delete set null,
  reference text not null unique,
  amount numeric(14,2) not null default 0,
  payment_method text,
  status text not null default 'initialized',
  additional_charge_ids text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists additional_charges_set_updated_at on public.additional_charges;
create trigger additional_charges_set_updated_at
before update on public.additional_charges
for each row execute procedure public.set_updated_at();

drop trigger if exists additional_charge_appeals_set_updated_at on public.additional_charge_appeals;
create trigger additional_charge_appeals_set_updated_at
before update on public.additional_charge_appeals
for each row execute procedure public.set_updated_at();

drop trigger if exists tenant_payments_set_updated_at on public.tenant_payments;
create trigger tenant_payments_set_updated_at
before update on public.tenant_payments
for each row execute procedure public.set_updated_at();

alter table public.lease_templates enable row level security;
alter table public.lease_documents enable row level security;
alter table public.additional_charges enable row level security;
alter table public.additional_charge_appeals enable row level security;
alter table public.tenant_payments enable row level security;

drop policy if exists lease_templates_policy on public.lease_templates;
create policy lease_templates_policy on public.lease_templates
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists lease_documents_policy on public.lease_documents;
create policy lease_documents_policy on public.lease_documents
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists additional_charges_policy on public.additional_charges;
create policy additional_charges_policy on public.additional_charges
for all using (
  auth.role() = 'authenticated'
  and (
    additional_charges.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = additional_charges.company_id
    )
  )
)
with check (
  auth.role() = 'authenticated'
  and (
    additional_charges.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = additional_charges.company_id
    )
  )
);

drop policy if exists additional_charge_appeals_policy on public.additional_charge_appeals;
create policy additional_charge_appeals_policy on public.additional_charge_appeals
for all using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists tenant_payments_policy on public.tenant_payments;
create policy tenant_payments_policy on public.tenant_payments
for all using (
  auth.role() = 'authenticated'
  and (
    tenant_payments.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = tenant_payments.company_id
    )
  )
)
with check (
  auth.role() = 'authenticated'
  and (
    tenant_payments.tenant_user_id = auth.uid()
    or exists (
      select 1
      from public.profiles current_profile
      where current_profile.id = auth.uid()
        and current_profile.company_id = tenant_payments.company_id
    )
  )
);

create table if not exists public.employment_statuses (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.document_types (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  category text,
  allowed_extensions text,
  max_file_size_bytes bigint,
  is_required boolean not null default false,
  is_system_type boolean not null default false,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists document_types_set_updated_at on public.document_types;
create trigger document_types_set_updated_at
before update on public.document_types
for each row execute procedure public.set_updated_at();

alter table public.employment_statuses enable row level security;
alter table public.document_types enable row level security;

drop policy if exists employment_statuses_read_policy on public.employment_statuses;
create policy employment_statuses_read_policy on public.employment_statuses
for select using (auth.role() = 'authenticated');

drop policy if exists document_types_read_policy on public.document_types;
create policy document_types_read_policy on public.document_types
for select using (auth.role() = 'authenticated');

drop policy if exists document_types_manage_policy on public.document_types;
create policy document_types_manage_policy on public.document_types
for all using (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
)
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.profiles current_profile
    where current_profile.id = auth.uid()
      and lower(current_profile.role) in ('owner', 'landlord', 'admin', 'property_manager', 'agent')
  )
);

insert into public.employment_statuses (code, name, description, is_active)
values
  ('full_time', 'full-time', 'Permanent full-time employment', true),
  ('part_time', 'part-time', 'Part-time employment', true),
  ('self_employed', 'self-employed', 'Self-employed or business owner', true),
  ('contract', 'contract', 'Fixed-term contract employment', true),
  ('retired', 'retired', 'Retired applicant', true),
  ('unemployed', 'unemployed', 'Currently unemployed', true),
  ('student', 'student', 'Full-time or part-time student', true)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    is_active = excluded.is_active;

insert into public.document_types (
  code,
  name,
  description,
  category,
  allowed_extensions,
  max_file_size_bytes,
  is_required,
  is_system_type,
  display_order,
  is_active
)
values
  ('id_copy', 'ID Copy', 'Government-issued identity document copy', 'identity', 'pdf,jpg,jpeg,png', 10485760, true, true, 10, true),
  ('payslip', 'Payslip', 'Recent payslip document', 'income', 'pdf', 10485760, true, true, 20, true),
  ('bank_statement', 'Bank Statement', 'Recent bank statement', 'income', 'pdf', 10485760, true, true, 30, true),
  ('proof_of_address', 'Proof of Address', 'Utility bill or proof of residence', 'identity', 'pdf,jpg,jpeg,png', 10485760, false, true, 40, true),
  ('employment_letter', 'Employment Letter', 'Employer confirmation letter', 'income', 'pdf', 10485760, false, true, 50, true),
  ('credit_report', 'Credit Report', 'Credit bureau report', 'verification', 'pdf', 10485760, false, true, 60, true)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    category = excluded.category,
    allowed_extensions = excluded.allowed_extensions,
    max_file_size_bytes = excluded.max_file_size_bytes,
    is_required = excluded.is_required,
    is_system_type = excluded.is_system_type,
    display_order = excluded.display_order,
    is_active = excluded.is_active;